# Generated by Django 4.1.2 on 2022-10-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='position',
            field=models.CharField(choices=[('G', 'Gerente'), ('V', 'Vendedor')], max_length=1, verbose_name='Cargo'),
        ),
    ]
